@extends('layouts.app')

@section('title', 'RVMS - Notifications')

{{-- BLOCK B: the prototype's markup (web/pages/notifications.html, whose rows are
     generated by agency.js renderNotificationsPage) with the hardcoded rows
     replaced by live data. Kept from the prototype: the Today / Yesterday /
     Earlier grouping, one card per group, empty groups rendering nothing, and the
     right-aligned time. Rows now post to notifications.open, which marks the
     notification read and redirects to the module it concerns — the prototype's
     .html hrefs 404 under real routing. Unread rows carry a leading dot and a
     tinted background: a documented addition, since the prototype has no
     read/unread distinction (its demo data has no state). --}}
@section('content')
                <div class="d-flex justify-content-between align-items-center mb-4">
                    <div>
                        <h3 class="fw-bold mb-0" style="color: var(--primary);">Notifications</h3>
                        <p class="text-secondary mb-0">All alerts and submissions for your agency</p>
                    </div>
                    <form method="POST" action="{{ route('notifications.read-all') }}">
                        @csrf
                        @method('PATCH')
                        <button type="submit" class="btn btn-light border fw-medium px-4 py-2 rounded-3" @disabled($unreadCount === 0)>
                            <i class="bi bi-check2-all me-2"></i>Mark All as Read
                        </button>
                    </form>
                </div>

                @include('partials.alerts')

                @foreach (['Today', 'Yesterday', 'Earlier'] as $group)
                    @if (($groups[$group] ?? collect())->isNotEmpty())
                <h6 class="fw-bold text-secondary text-uppercase small mb-3">{{ $group }}</h6>
                <div class="card border-0 shadow-sm rounded-3 overflow-hidden mb-4"><div class="list-group list-group-flush">
                        @foreach ($groups[$group] as $notification)
                    <form method="POST" action="{{ route('notifications.open', $notification) }}">
                        @csrf
                        <button type="submit" class="list-group-item list-group-item-action d-flex align-items-start gap-3 py-3 w-100 text-start border-0 {{ $notification->is_read ? '' : 'bg-light' }}">
                            <span class="notif-icon rounded-circle bg-{{ $notification->tone() }} bg-opacity-10 text-{{ $notification->tone() }} d-inline-flex justify-content-center align-items-center mt-1"><i class="bi {{ $notification->icon() }}"></i></span>
                            <span class="flex-grow-1"><span class="fw-bold d-block">@unless ($notification->is_read)<i class="bi bi-circle-fill text-primary me-2" style="font-size: 0.4rem; vertical-align: middle;"></i>@endunless{{ $notification->title }}</span><span class="small text-secondary d-block">{{ $notification->message }}</span></span>
                            <span class="small text-secondary text-nowrap">{{ $notification->timeLabel() }}</span>
                        </button>
                    </form>
                        @endforeach
                </div></div>
                    @endif
                @endforeach

                @if ($groups->isEmpty())
                <div class="card border-0 shadow-sm rounded-3">
                    <div class="card-body text-center text-secondary py-5">
                        <i class="bi bi-bell-slash fs-1 d-block mb-3 opacity-50"></i>
                        No notifications yet. Alerts for damage reports, flagged inspections,
                        access requests, licences and preventive maintenance will appear here.
                    </div>
                </div>
                @endif
@endsection
