@extends('layouts.app')

@section('title', 'RVMS - Reports')

{{-- BLOCK B: the prototype's markup (web/pages/reports.html) with the demo
     JavaScript replaced by a real GET to this same route. The six type cards,
     the Configure Report modal and the rendered report keep the prototype's
     structure and wording exactly; the report body now comes from
     App\Services\ReportBuilder, which GET /api/v1/reports/{type} shares.

     Two documented deviations:
       · the printout is stamped "Generated by <admin>" as well as the date —
         FR-20 requires a report to record WHO produced it, and the prototype's
         header shows only a date;
       · each report carries every field its module records (project lead,
         2026-07), so the tables are wider than the prototype's demo columns. --}}
@section('content')
                <div class="d-flex justify-content-between align-items-center mb-4">
                    <div>
                        <h3 class="fw-bold mb-0" style="color: var(--primary);">Report Generation</h3>
                        <p class="text-secondary mb-0">Generate print-ready system reports</p>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-4 mb-4">
                        <div class="card border-0 shadow-sm rounded-3 h-100">
                            <div class="card-body p-4 text-center">
                                <div class="bg-primary bg-opacity-10 text-primary rounded-circle d-inline-flex p-4 mb-3">
                                    <i class="bi bi-clipboard-check fs-1"></i>
                                </div>
                                <h5 class="fw-bold">Inspection Records</h5>
                                <p class="text-secondary small mb-4">Export BLOWBAGETS checklists</p>
                                <button class="btn btn-outline-primary w-100" data-bs-toggle="modal" data-bs-target="#configureReportModal" data-report-type="Inspection Records" data-report-slug="inspections">Configure Report</button>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4 mb-4">
                        <div class="card border-0 shadow-sm rounded-3 h-100">
                            <div class="card-body p-4 text-center">
                                <div class="bg-primary bg-opacity-10 text-primary rounded-circle d-inline-flex p-4 mb-3">
                                    <i class="bi bi-file-earmark-medical fs-1"></i>
                                </div>
                                <h5 class="fw-bold">Damage & Defects</h5>
                                <p class="text-secondary small mb-4">Export reported damages and resolutions</p>
                                <button class="btn btn-outline-primary w-100" data-bs-toggle="modal" data-bs-target="#configureReportModal" data-report-type="Damage & Defects" data-report-slug="damage">Configure Report</button>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4 mb-4">
                        <div class="card border-0 shadow-sm rounded-3 h-100">
                            <div class="card-body p-4 text-center">
                                <div class="bg-primary bg-opacity-10 text-primary rounded-circle d-inline-flex p-4 mb-3">
                                    <i class="bi bi-tools fs-1"></i>
                                </div>
                                <h5 class="fw-bold">Repair & Maintenance History</h5>
                                <p class="text-secondary small mb-4">Export repair logs by vehicle and repair source</p>
                                <button class="btn btn-outline-primary w-100" data-bs-toggle="modal" data-bs-target="#configureReportModal" data-report-type="Repair & Maintenance History" data-report-slug="repairs-maintenance">Configure Report</button>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4 mb-4">
                        <div class="card border-0 shadow-sm rounded-3 h-100">
                            <div class="card-body p-4 text-center">
                                <div class="bg-primary bg-opacity-10 text-primary rounded-circle d-inline-flex p-4 mb-3">
                                    <i class="bi bi-wrench-adjustable-circle fs-1"></i>
                                </div>
                                <h5 class="fw-bold">Preventive Maintenance Records</h5>
                                <p class="text-secondary small mb-4">Export PM schedules and completion records</p>
                                <button class="btn btn-outline-primary w-100" data-bs-toggle="modal" data-bs-target="#configureReportModal" data-report-type="Preventive Maintenance Records" data-report-slug="pm">Configure Report</button>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4 mb-4">
                        <div class="card border-0 shadow-sm rounded-3 h-100">
                            <div class="card-body p-4 text-center">
                                <div class="bg-primary bg-opacity-10 text-primary rounded-circle d-inline-flex p-4 mb-3">
                                    <i class="bi bi-send-check fs-1"></i>
                                </div>
                                <h5 class="fw-bold">Dispatch Logs</h5>
                                <p class="text-secondary small mb-4">Export fleet deployment history</p>
                                <button class="btn btn-outline-primary w-100" data-bs-toggle="modal" data-bs-target="#configureReportModal" data-report-type="Dispatch Logs" data-report-slug="dispatch">Configure Report</button>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4 mb-4">
                        <div class="card border-0 shadow-sm rounded-3 h-100">
                            <div class="card-body p-4 text-center">
                                <div class="bg-primary bg-opacity-10 text-primary rounded-circle d-inline-flex p-4 mb-3">
                                    <i class="bi bi-truck fs-1"></i>
                                </div>
                                <h5 class="fw-bold">Vehicle Status Summary</h5>
                                <p class="text-secondary small mb-4">Current snapshot of all vehicles — no filters</p>
                                <button class="btn btn-outline-primary w-100" data-bs-toggle="modal" data-bs-target="#configureReportModal" data-report-type="Vehicle Status Summary" data-report-slug="vehicle-status">Configure Report</button>
                            </div>
                        </div>
                    </div>
                </div>

                <!-- Generated report renders here -->
                <div id="reportOutput">
                @if ($report)
                    {{-- The prototype's own print-area markup, filled from real records.
                         `no-print` on the buttons is the prototype's class; style.css
                         already carries the @media print rules. --}}
                    <div id="reportPrintArea" class="card border-0 shadow-sm rounded-3 mb-4">
                        <div class="card-body p-4">
                            <div class="d-flex justify-content-between align-items-start border-bottom pb-3 mb-3">
                                <div class="d-flex align-items-center gap-3">
                                    <img src="{{ asset(auth()->user()->agency->logo_path) }}" alt="" class="agency-logo-img">
                                    <div>
                                        <div class="fw-bold fs-5" style="color:var(--primary);">{{ auth()->user()->agency->name }}</div>
                                        <div class="small text-secondary">Rescue Vehicle Management System &middot; {{ auth()->user()->agency->location }}</div>
                                    </div>
                                </div>
                                <div class="text-end">
                                    <div class="fw-bold">{{ $report['title'] }}</div>
                                    {{-- FR-20: the report records WHO generated it and WHEN. The
                                         prototype header carries only the date. --}}
                                    <div class="small text-secondary">Generated: {{ $generatedAt->format('F j, Y') }}</div>
                                    <div class="small text-secondary">Generated by: {{ $generatedBy->name }}</div>
                                </div>
                            </div>
                            <div class="small text-secondary mb-3">{!! implode(' &nbsp;&middot;&nbsp; ', array_map('e', $report['filter_summary'])) !!}</div>
                            <div class="table-responsive">
                                <table class="table table-sm table-bordered align-middle mb-0">
                                    <thead class="table-light"><tr>
                                        @foreach ($report['columns'] as $column)
                                        <th>{{ $column }}</th>
                                        @endforeach
                                    </tr></thead>
                                    <tbody>
                                        @forelse ($report['rows'] as $row)
                                        <tr>
                                            @foreach ($row as $cell)
                                            <td>{{ $cell }}</td>
                                            @endforeach
                                        </tr>
                                        @empty
                                        <tr><td colspan="{{ count($report['columns']) }}" class="text-center text-secondary py-4">No records match the selected filters.</td></tr>
                                        @endforelse
                                    </tbody>
                                </table>
                            </div>
                            <div class="small text-secondary mt-3">{{ count($report['rows']) }} {{ Str::plural('record', count($report['rows'])) }} &middot; Report based solely on data encoded in the system.</div>
                        </div>
                    </div>
                    <div class="d-flex gap-2 mb-4 no-print">
                        <button type="button" class="btn bg-navy text-white" onclick="window.print()"><i class="bi bi-printer me-2"></i>Print / Save as PDF</button>
                        <a href="{{ route('reports') }}" class="btn btn-light border">Clear</a>
                    </div>
                @endif
                </div>

@endsection

@section('modals')
    <!-- Configure Report Modal -->
    <div class="modal fade" id="configureReportModal" tabindex="-1">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header bg-navy text-white">
                    <h5 class="modal-title fw-bold">Configure Report</h5>
                    <button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal"></button>
                </div>
                <div class="modal-body p-4">
                    <div class="bg-light rounded-3 p-3 mb-3">
                        <div class="small text-secondary">Report Type</div>
                        <div class="fw-bold" id="rpTitle">Inspection Records</div>
                    </div>
                    <form id="reportForm" method="GET" action="{{ route('reports') }}">
                        <input type="hidden" name="type" id="rpType" value="inspections">
                        <div id="rpFilters">
                            <div class="mb-3">
                                <label class="form-label fw-semibold">Date Range</label>
                                <select class="form-select" id="rpRange" name="range">
                                    @foreach (\App\Services\ReportBuilder::RANGES as $value => $label)
                                    <option value="{{ $value }}" @selected(request('range', 'all') === $value)>{{ $label }}</option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="row g-2 mb-3">
                                <div class="col-6">
                                    <label class="form-label fw-semibold">Vehicle</label>
                                    <select class="form-select js-vehicle-options" id="rpVehicle" name="vehicle_id" data-keep-first="true">
                                        <option value="">All Vehicles</option>
                                        @foreach ($vehicles as $vehicle)
                                        <option value="{{ $vehicle->id }}" @selected((string) request('vehicle_id') === (string) $vehicle->id)>{{ $vehicle->plate_number }} ({{ $vehicle->type }})</option>
                                        @endforeach
                                    </select>
                                </div>
                                <div class="col-6">
                                    <label class="form-label fw-semibold">Driver</label>
                                    <select class="form-select js-driver-options" id="rpDriver" name="driver_id" data-keep-first="true">
                                        <option value="">All Drivers</option>
                                        @foreach ($drivers as $driver)
                                        <option value="{{ $driver->id }}" @selected((string) request('driver_id') === (string) $driver->id)>{{ $driver->name }}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                        </div>
                        <div class="form-text"><i class="bi bi-info-circle me-1"></i>The report is generated from this agency's encoded records and opens below, ready to print or save as PDF.</div>
                    </form>
                </div>
                <div class="modal-footer border-0">
                    <button type="button" class="btn btn-light border" data-bs-dismiss="modal">Cancel</button>
                    <button type="submit" form="reportForm" class="btn bg-navy text-white" id="rpGenerate">Generate Report</button>
                </div>
            </div>
        </div>
    </div>

{{-- The prototype's wireReports(): the clicked card decides the report type and
     which filters apply. Wrapped in DOMContentLoaded per the layout's script
     rules, and Bootstrap is already loaded by the time @yield('modals') runs. --}}
<script>
document.addEventListener('DOMContentLoaded', function () {
    const modal = document.getElementById('configureReportModal');
    if (!modal) return;

    // Vehicle Status Summary is a current snapshot — the prototype hides the
    // whole filter block for it. PM schedules have no driver of their own.
    const UNFILTERED = ['vehicle-status'];
    const NO_DRIVER = ['pm', 'vehicle-status'];

    modal.addEventListener('show.bs.modal', function (event) {
        const btn = event.relatedTarget;
        if (!btn) return;

        const slug = btn.dataset.reportSlug;
        const title = btn.dataset.reportType;

        document.getElementById('rpType').value = slug;
        document.getElementById('rpTitle').textContent = title;

        const filters = document.getElementById('rpFilters');
        if (filters) filters.style.display = UNFILTERED.includes(slug) ? 'none' : '';

        const driver = document.getElementById('rpDriver');
        if (driver) {
            const cell = driver.closest('.col-6');
            if (cell) cell.style.display = NO_DRIVER.includes(slug) ? 'none' : '';
            // A hidden select must not submit a stale id from a previous report.
            if (NO_DRIVER.includes(slug)) driver.value = '';
        }
    });
});
</script>
@endsection
